//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffee.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CancelOrder
    {
        public int CancelID { get; set; }
        [Required]
        public int OrderID { get; set; }
        public int CanceledBy { get; set; }

        [Required(ErrorMessage = "Vui lòng nhập lý do huỷ đơn.")]
        [StringLength(255)]
        public string Reason { get; set; }
        public string CancelReason { get; set; }
        public System.DateTime CancelDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual Order Order { get; set; }
    }
}
