//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCoffee.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Rating1 { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int ProductID { get; set; }
        public int OrderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
